name: matrix release
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win, linux, win32]
        stack: [app, staging, staging2]
        profile: [aliyun-prod, default]
        exclude:
          - stack: staging2
            profile: default
          - stack: staging
            profile: aliyun-prod
    steps:
      - name: build
        run: |
          echo "${{matrix.platform}} ${{matrix.profile}} ${{ matrix.stack }}"
          echo "win = ${{matrix.platform == 'win'}}"
